const gameData = [
    // ======================================================
    // LEVEL 0: SUPER SIMPLE (3 BLOCKS ONLY)
    // Target: Very weak students. 
    // Logic: [Subject Group] + [Verb Group] + [Object/Rest]
    // ======================================================
    { id: 100, level: 0, correct: "The big dog chased the cat.", blocks: ["The big dog", "chased", "the cat."], hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 101, level: 0, correct: "My mother is cooking dinner.", blocks: ["My mother", "is cooking", "dinner."], hint: "Subject + Verb + Object", feedback: "Good job." },
    { id: 102, level: 0, correct: "The bird sat on the tree.", blocks: ["The bird", "sat", "on the tree."], hint: "Subject + Verb + Place", feedback: "Correct." },
    { id: 103, level: 0, correct: "He plays football.", blocks: ["He", "plays", "football."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 104, level: 0, correct: "The students are reading books.", blocks: ["The students", "are reading", "books."], hint: "Who is reading?", feedback: "Correct." },
    { id: 105, level: 0, correct: "A cat sleeps on the sofa.", blocks: ["A cat", "sleeps", "on the sofa."], hint: "Subject + Verb + Place", feedback: "Correct." },
    { id: 106, level: 0, correct: "Mr. Smith drives a red car.", blocks: ["Mr. Smith", "drives", "a red car."], hint: "Person + Action + Object", feedback: "Correct." },
    { id: 107, level: 0, correct: "We went to the park.", blocks: ["We", "went", "to the park."], hint: "Subject + Verb + Place", feedback: "Correct." },
    { id: 108, level: 0, correct: "The sun is hot.", blocks: ["The sun", "is", "hot."], hint: "Subject + Verb + Adjective", feedback: "Correct." },
    { id: 109, level: 0, correct: "She loves ice cream.", blocks: ["She", "loves", "ice cream."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 110, level: 0, correct: "The baby is crying loudly.", blocks: ["The baby", "is crying", "loudly."], hint: "Subject + Verb + Adverb", feedback: "Correct." },
    { id: 111, level: 0, correct: "My dad washes the car.", blocks: ["My dad", "washes", "the car."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 112, level: 0, correct: "The teacher writes on the board.", blocks: ["The teacher", "writes", "on the board."], hint: "Subject + Verb + Place", feedback: "Correct." },
    { id: 113, level: 0, correct: "I like apples.", blocks: ["I", "like", "apples."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 114, level: 0, correct: "The rain falls down.", blocks: ["The rain", "falls", "down."], hint: "Subject + Verb + Direction", feedback: "Correct." },
    { id: 115, level: 0, correct: "A fish swims in the water.", blocks: ["A fish", "swims", "in the water."], hint: "Subject + Verb + Place", feedback: "Correct." },
    { id: 116, level: 0, correct: "The boy kicks the ball.", blocks: ["The boy", "kicks", "the ball."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 117, level: 0, correct: "We are happy.", blocks: ["We", "are", "happy."], hint: "Subject + Verb + Adjective", feedback: "Correct." },
    { id: 118, level: 0, correct: "The girl sings a song.", blocks: ["The girl", "sings", "a song."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 119, level: 0, correct: "They run fast.", blocks: ["They", "run", "fast."], hint: "Subject + Verb + Adverb", feedback: "Correct." },
    { id: 120, level: 0, correct: "My brother eats pizza.", blocks: ["My brother", "eats", "pizza."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 121, level: 0, correct: "The cow eats grass.", blocks: ["The cow", "eats", "grass."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 122, level: 0, correct: "I drink water.", blocks: ["I", "drink", "water."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 123, level: 0, correct: "The bus arrives late.", blocks: ["The bus", "arrives", "late."], hint: "Subject + Verb + Time", feedback: "Correct." },
    { id: 124, level: 0, correct: "She opens the door.", blocks: ["She", "opens", "the door."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 125, level: 0, correct: "He closes the window.", blocks: ["He", "closes", "the window."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 126, level: 0, correct: "The phone is ringing.", blocks: ["The phone", "is", "ringing."], hint: "Subject + Verb + Action", feedback: "Correct." },
    { id: 127, level: 0, correct: "We watch TV.", blocks: ["We", "watch", "TV."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 128, level: 0, correct: "The stars shine brightly.", blocks: ["The stars", "shine", "brightly."], hint: "Subject + Verb + Adverb", feedback: "Correct." },
    { id: 129, level: 0, correct: "A dog barks loudly.", blocks: ["A dog", "barks", "loudly."], hint: "Subject + Verb + Adverb", feedback: "Correct." },
    { id: 130, level: 0, correct: "The car stopped here.", blocks: ["The car", "stopped", "here."], hint: "Subject + Verb + Place", feedback: "Correct." },
    { id: 131, level: 0, correct: "My friend is nice.", blocks: ["My friend", "is", "nice."], hint: "Subject + Verb + Adjective", feedback: "Correct." },
    { id: 132, level: 0, correct: "The flower smells good.", blocks: ["The flower", "smells", "good."], hint: "Subject + Verb + Adjective", feedback: "Correct." },
    { id: 133, level: 0, correct: "I have a pen.", blocks: ["I", "have", "a pen."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 134, level: 0, correct: "You look tired.", blocks: ["You", "look", "tired."], hint: "Subject + Verb + Adjective", feedback: "Correct." },
    { id: 135, level: 0, correct: "The plane flies high.", blocks: ["The plane", "flies", "high."], hint: "Subject + Verb + Adverb", feedback: "Correct." },
    { id: 136, level: 0, correct: "We study English.", blocks: ["We", "study", "English."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 137, level: 0, correct: "The cat saw a mouse.", blocks: ["The cat", "saw", "a mouse."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 138, level: 0, correct: "He wears a hat.", blocks: ["He", "wears", "a hat."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 139, level: 0, correct: "She buys milk.", blocks: ["She", "buys", "milk."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 140, level: 0, correct: "The fire is hot.", blocks: ["The fire", "is", "hot."], hint: "Subject + Verb + Adjective", feedback: "Correct." },
    { id: 141, level: 0, correct: "Snow is cold.", blocks: ["Snow", "is", "cold."], hint: "Subject + Verb + Adjective", feedback: "Correct." },
    { id: 142, level: 0, correct: "The monkey eats a banana.", blocks: ["The monkey", "eats", "a banana."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 143, level: 0, correct: "I walk to school.", blocks: ["I", "walk", "to school."], hint: "Subject + Verb + Place", feedback: "Correct." },

    { id: 145, level: 0, correct: "They dance well.", blocks: ["They", "dance", "well."], hint: "Subject + Verb + Adverb", feedback: "Correct." },
    { id: 146, level: 0, correct: "The lamp is bright.", blocks: ["The lamp", "is", "bright."], hint: "Subject + Verb + Adjective", feedback: "Correct." },
    { id: 147, level: 0, correct: "He fixed the bike.", blocks: ["He", "fixed", "the bike."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 148, level: 0, correct: "We love games.", blocks: ["We", "love", "games."], hint: "Subject + Verb + Object", feedback: "Correct." },
    { id: 149, level: 0, correct: "The ship sails away.", blocks: ["The ship", "sails", "away."], hint: "Subject + Verb + Direction", feedback: "Correct." },

    // ======================================================
    // LEVEL 1: SIMPLE SVO (Word by Word)
    // ======================================================
    { id: 200, level: 1, correct: "The dog chased the cat.", hint: "Who chased whom?", feedback: "Correct!" },
    { id: 201, level: 1, correct: "Birds fly in the sky.", hint: "Subject + Verb + Place", feedback: "Correct!" },
    { id: 202, level: 1, correct: "She reads a book.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 203, level: 1, correct: "He plays the guitar.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 204, level: 1, correct: "They ate pizza.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 205, level: 1, correct: "I drink coffee.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 206, level: 1, correct: "Fish swim in water.", hint: "Subject + Verb + Place", feedback: "Correct!" },
    { id: 207, level: 1, correct: "We bought a car.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 208, level: 1, correct: "I forgot my keys.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 209, level: 1, correct: "She brushed her hair.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 210, level: 1, correct: "The sun shines.", hint: "Subject + Verb", feedback: "Correct!" },
    { id: 211, level: 1, correct: "He runs very fast.", hint: "Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 212, level: 1, correct: "I like blue cars.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 213, level: 1, correct: "They play outside.", hint: "Subject + Verb + Place", feedback: "Correct!" },
    { id: 214, level: 1, correct: "We saw a movie.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 215, level: 1, correct: "She cooks dinner.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 216, level: 1, correct: "He kicked the ball.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 217, level: 1, correct: "I have two dogs.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 218, level: 1, correct: "The cat is black.", hint: "Subject + Verb + Adjective", feedback: "Correct!" },
    { id: 219, level: 1, correct: "You are my friend.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 220, level: 1, correct: "It rains a lot.", hint: "Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 221, level: 1, correct: "We walk to school.", hint: "Subject + Verb + Place", feedback: "Correct!" },
    { id: 222, level: 1, correct: "She sings well.", hint: "Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 223, level: 1, correct: "He works hard.", hint: "Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 224, level: 1, correct: "The baby sleeps.", hint: "Subject + Verb", feedback: "Correct!" },
    { id: 225, level: 1, correct: "I want an apple.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 226, level: 1, correct: "They need help.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 227, level: 1, correct: "We love summer.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 228, level: 1, correct: "The car is fast.", hint: "Subject + Verb + Adjective", feedback: "Correct!" },
    { id: 229, level: 1, correct: "She writes a letter.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 230, level: 1, correct: "He opened the box.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 231, level: 1, correct: "I lost my bag.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 232, level: 1, correct: "They built a house.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 233, level: 1, correct: "We cleaned the room.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 234, level: 1, correct: "The door is open.", hint: "Subject + Verb + Adjective", feedback: "Correct!" },
    { id: 235, level: 1, correct: "She wears a dress.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 236, level: 1, correct: "He found a coin.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 237, level: 1, correct: "I hear a noise.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 238, level: 1, correct: "They sell fruit.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 239, level: 1, correct: "We sat down.", hint: "Subject + Verb + Direction", feedback: "Correct!" },
    { id: 240, level: 1, correct: "The light is green.", hint: "Subject + Verb + Adjective", feedback: "Correct!" },
    { id: 241, level: 1, correct: "She drew a picture.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 242, level: 1, correct: "He broke the cup.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 243, level: 1, correct: "I made a cake.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 244, level: 1, correct: "They went home.", hint: "Subject + Verb + Place", feedback: "Correct!" },
    { id: 245, level: 1, correct: "We like music.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 246, level: 1, correct: "The water is cold.", hint: "Subject + Verb + Adjective", feedback: "Correct!" },
    { id: 247, level: 1, correct: "She called me.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 248, level: 1, correct: "He paid the bill.", hint: "Subject + Verb + Object", feedback: "Correct!" },
    { id: 249, level: 1, correct: "I read the news.", hint: "Subject + Verb + Object", feedback: "Correct!" },

    // ======================================================
    // LEVEL 2: PROPER NOUNS & BLOCKS
    // ======================================================
    { id: 300, level: 2, correct: "I visited New York.", blocks: ["I", "visited", "New York."], hint: "City name stays together.", feedback: "Correct!" },
    { id: 301, level: 2, correct: "Mr. Smith teaches math.", blocks: ["Mr. Smith", "teaches", "math."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 302, level: 2, correct: "They live in the United Kingdom.", blocks: ["They", "live", "in", "the", "United Kingdom."], hint: "Country name stays together.", feedback: "Correct!" },
    { id: 303, level: 2, correct: "Harry Potter is a wizard.", blocks: ["Harry Potter", "is", "a", "wizard."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 304, level: 2, correct: "We ate at Burger King.", blocks: ["We", "ate", "at", "Burger King."], hint: "Restaurant name stays together.", feedback: "Correct!" },
    { id: 305, level: 2, correct: "Santa Claus brings gifts.", blocks: ["Santa Claus", "brings", "gifts."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 306, level: 2, correct: "The Eiffel Tower is tall.", blocks: ["The", "Eiffel Tower", "is", "tall."], hint: "Landmark name stays together.", feedback: "Correct!" },
    { id: 307, level: 2, correct: "Mrs. Jones is nice.", blocks: ["Mrs. Jones", "is", "nice."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 308, level: 2, correct: "I love Star Wars.", blocks: ["I", "love", "Star Wars."], hint: "Movie title stays together.", feedback: "Correct!" },
    { id: 309, level: 2, correct: "He drives a Ford Mustang.", blocks: ["He", "drives", "a", "Ford Mustang."], hint: "Car name stays together.", feedback: "Correct!" },
    { id: 310, level: 2, correct: "We flew to Los Angeles.", blocks: ["We", "flew", "to", "Los Angeles."], hint: "City name stays together.", feedback: "Correct!" },
    { id: 311, level: 2, correct: "Dr. Phil is on TV.", blocks: ["Dr. Phil", "is", "on", "TV."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 312, level: 2, correct: "She works at Taco Bell.", blocks: ["She", "works", "at", "Taco Bell."], hint: "Restaurant name stays together.", feedback: "Correct!" },
    { id: 313, level: 2, correct: "Mount Everest is high.", blocks: ["Mount Everest", "is", "high."], hint: "Mountain name stays together.", feedback: "Correct!" },
    { id: 314, level: 2, correct: "I met Captain America.", blocks: ["I", "met", "Captain America."], hint: "Hero name stays together.", feedback: "Correct!" },
    { id: 315, level: 2, correct: "They went to Disney World.", blocks: ["They", "went", "to", "Disney World."], hint: "Place name stays together.", feedback: "Correct!" },
    { id: 316, level: 2, correct: "Mr. Bean is funny.", blocks: ["Mr. Bean", "is", "funny."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 317, level: 2, correct: "We saw the Golden Gate Bridge.", blocks: ["We", "saw", "the", "Golden Gate Bridge."], hint: "Bridge name stays together.", feedback: "Correct!" },
    { id: 318, level: 2, correct: "He reads The New York Times.", blocks: ["He", "reads", "The New York Times."], hint: "Newspaper name stays together.", feedback: "Correct!" },
    { id: 319, level: 2, correct: "Queen Elizabeth was famous.", blocks: ["Queen Elizabeth", "was", "famous."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 320, level: 2, correct: "I use Microsoft Windows.", blocks: ["I", "use", "Microsoft Windows."], hint: "Software name stays together.", feedback: "Correct!" },
    { id: 321, level: 2, correct: "They speak Mandarin Chinese.", blocks: ["They", "speak", "Mandarin Chinese."], hint: "Language name stays together.", feedback: "Correct!" },
    { id: 322, level: 2, correct: "We visited the Grand Canyon.", blocks: ["We", "visited", "the", "Grand Canyon."], hint: "Place name stays together.", feedback: "Correct!" },
    { id: 323, level: 2, correct: "Miss White is singing.", blocks: ["Miss White", "is", "singing."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 324, level: 2, correct: "He likes Coca Cola.", blocks: ["He", "likes", "Coca Cola."], hint: "Drink name stays together.", feedback: "Correct!" },
    { id: 325, level: 2, correct: "She lives in South Africa.", blocks: ["She", "lives", "in", "South Africa."], hint: "Country name stays together.", feedback: "Correct!" },
    { id: 326, level: 2, correct: "I watched Spongebob Squarepants.", blocks: ["I", "watched", "Spongebob Squarepants."], hint: "Show name stays together.", feedback: "Correct!" },
    { id: 327, level: 2, correct: "We stayed at the Hilton Hotel.", blocks: ["We", "stayed", "at", "the", "Hilton Hotel."], hint: "Hotel name stays together.", feedback: "Correct!" },
    { id: 328, level: 2, correct: "Tom Cruise is an actor.", blocks: ["Tom Cruise", "is", "an", "actor."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 329, level: 2, correct: "The White House is big.", blocks: ["The White House", "is", "big."], hint: "Building name stays together.", feedback: "Correct!" },
    { id: 330, level: 2, correct: "I play Super Mario.", blocks: ["I", "play", "Super Mario."], hint: "Game name stays together.", feedback: "Correct!" },
    { id: 331, level: 2, correct: "He is from Saudi Arabia.", blocks: ["He", "is", "from", "Saudi Arabia."], hint: "Country name stays together.", feedback: "Correct!" },
    { id: 332, level: 2, correct: "She bought a Louis Vuitton bag.", blocks: ["She", "bought", "a", "Louis Vuitton", "bag."], hint: "Brand name stays together.", feedback: "Correct!" },
    { id: 333, level: 2, correct: "We crossed the Atlantic Ocean.", blocks: ["We", "crossed", "the", "Atlantic Ocean."], hint: "Ocean name stays together.", feedback: "Correct!" },
    { id: 334, level: 2, correct: "Uncle Sam wants you.", blocks: ["Uncle Sam", "wants", "you."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 335, level: 2, correct: "The Red Cross helps people.", blocks: ["The Red Cross", "helps", "people."], hint: "Organization name stays together.", feedback: "Correct!" },
    { id: 336, level: 2, correct: "I listen to Taylor Swift.", blocks: ["I", "listen", "to", "Taylor Swift."], hint: "Singer name stays together.", feedback: "Correct!" },
    { id: 337, level: 2, correct: "They went to Las Vegas.", blocks: ["They", "went", "to", "Las Vegas."], hint: "City name stays together.", feedback: "Correct!" },
    { id: 338, level: 2, correct: "Prince William is royal.", blocks: ["Prince William", "is", "royal."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 339, level: 2, correct: "We saw the Mona Lisa.", blocks: ["We", "saw", "the", "Mona Lisa."], hint: "Art name stays together.", feedback: "Correct!" },
    { id: 340, level: 2, correct: "He studies at Oxford University.", blocks: ["He", "studies", "at", "Oxford University."], hint: "School name stays together.", feedback: "Correct!" },
    { id: 341, level: 2, correct: "She likes dark chocolate.", blocks: ["She", "likes", "dark chocolate."], hint: "Type of chocolate stays together.", feedback: "Correct!" },
    { id: 342, level: 2, correct: "The North Pole is cold.", blocks: ["The North Pole", "is", "cold."], hint: "Place name stays together.", feedback: "Correct!" },
    { id: 343, level: 2, correct: "I read Harry Potter.", blocks: ["I", "read", "Harry Potter."], hint: "Book title stays together.", feedback: "Correct!" },
    { id: 344, level: 2, correct: "We drove to San Francisco.", blocks: ["We", "drove", "to", "San Francisco."], hint: "City name stays together.", feedback: "Correct!" },
    { id: 345, level: 2, correct: "Mr. Rogers was kind.", blocks: ["Mr. Rogers", "was", "kind."], hint: "Name stays together.", feedback: "Correct!" },
    { id: 346, level: 2, correct: "The Amazon River is long.", blocks: ["The Amazon River", "is", "long."], hint: "River name stays together.", feedback: "Correct!" },
    { id: 347, level: 2, correct: "I want Pizza Hut.", blocks: ["I", "want", "Pizza Hut."], hint: "Brand name stays together.", feedback: "Correct!" },
    { id: 348, level: 2, correct: "They visited Hong Kong.", blocks: ["They", "visited", "Hong Kong."], hint: "City name stays together.", feedback: "Correct!" },
    { id: 349, level: 2, correct: "Doctor Strange is magic.", blocks: ["Doctor Strange", "is", "magic."], hint: "Name stays together.", feedback: "Correct!" },

    // ======================================================
    // LEVEL 3: ADJECTIVES & COMPLEX
    // ======================================================
    { id: 400, level: 3, correct: "The big red truck stopped.", hint: "Adjectives before noun.", feedback: "Correct!" },
    { id: 401, level: 3, correct: "A black cat jumped over the fence.", hint: "Subject + Verb + Preposition + Object", feedback: "Correct!" },
    { id: 402, level: 3, correct: "My sister cooks delicious food.", hint: "Adjective describes food.", feedback: "Correct!" },
    { id: 403, level: 3, correct: "The tired student fell asleep.", hint: "Adjective describes student.", feedback: "Correct!" },
    { id: 404, level: 3, correct: "He opened the door slowly.", hint: "Adverb at the end.", feedback: "Correct!" },
    { id: 405, level: 3, correct: "The wind blew the leaves away.", hint: "Subject + Verb + Object + Adverb", feedback: "Correct!" },
    { id: 406, level: 3, correct: "The police officer stopped the traffic.", blocks: ["The", "police officer", "stopped", "the", "traffic."], hint: "Compound noun.", feedback: "Correct!" },
    { id: 407, level: 3, correct: "The train arrived very late.", hint: "Adverb phrase at end.", feedback: "Correct!" },
    { id: 408, level: 3, correct: "She wears glasses to read.", hint: "Reason at the end.", feedback: "Correct!" },
    { id: 409, level: 3, correct: "The small dog barked loudly.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 410, level: 3, correct: "I saw a beautiful rainbow.", hint: "Adjective before noun.", feedback: "Correct!" },
    { id: 411, level: 3, correct: "The old man walked slowly.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 412, level: 3, correct: "She bought a new blue dress.", hint: "Order of adjectives.", feedback: "Correct!" },
    { id: 413, level: 3, correct: "He carefully painted the wall.", hint: "Adverb before verb.", feedback: "Correct!" },
    { id: 414, level: 3, correct: "The hungry lion roared loudly.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 415, level: 3, correct: "We sat on the comfortable sofa.", hint: "Adjective before noun.", feedback: "Correct!" },
    { id: 416, level: 3, correct: "The fast car zoomed past us.", hint: "Adjective + Subject + Verb + Preposition", feedback: "Correct!" },
    { id: 417, level: 3, correct: "She gently held the baby.", hint: "Adverb before verb.", feedback: "Correct!" },
    { id: 418, level: 3, correct: "He ate the spicy curry quickly.", hint: "Adjective before noun, Adverb at end.", feedback: "Correct!" },
    { id: 419, level: 3, correct: "The tall trees swayed in the wind.", hint: "Adjective + Subject + Verb + Phrase", feedback: "Correct!" },
    { id: 420, level: 3, correct: "I lost my favorite red pen.", hint: "Two adjectives.", feedback: "Correct!" },
    { id: 421, level: 3, correct: "The angry customer shouted loudly.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 422, level: 3, correct: "She has long brown hair.", hint: "Order of adjectives.", feedback: "Correct!" },
    { id: 423, level: 3, correct: "He lives in a small white house.", hint: "Order of adjectives.", feedback: "Correct!" },
    { id: 424, level: 3, correct: "The happy children played outside.", hint: "Adjective + Subject + Verb + Place", feedback: "Correct!" },
    { id: 425, level: 3, correct: "A large bird flew over us.", hint: "Adjective + Subject + Verb + Preposition", feedback: "Correct!" },
    { id: 426, level: 3, correct: "The cold snow fell softly.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 427, level: 3, correct: "She wrote a very long letter.", hint: "Adverb + Adjective + Noun", feedback: "Correct!" },
    { id: 428, level: 3, correct: "He solved the hard puzzle easily.", hint: "Adjective + Noun, Adverb at end.", feedback: "Correct!" },
    { id: 429, level: 3, correct: "The brave knight fought the dragon.", hint: "Adjective + Subject + Verb + Object", feedback: "Correct!" },
    { id: 430, level: 3, correct: "I drank the cold sweet tea.", hint: "Two adjectives.", feedback: "Correct!" },
    { id: 431, level: 3, correct: "The busy bees made honey.", hint: "Adjective + Subject + Verb + Object", feedback: "Correct!" },
    { id: 432, level: 3, correct: "She wore a shiny gold ring.", hint: "Two adjectives.", feedback: "Correct!" },
    { id: 433, level: 3, correct: "He drove the car very carefully.", hint: "Adverb phrase at end.", feedback: "Correct!" },
    { id: 434, level: 3, correct: "The scary movie ended finally.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 435, level: 3, correct: "We walked through the dark forest.", hint: "Adjective before noun.", feedback: "Correct!" },
    { id: 436, level: 3, correct: "The smart girl answered correctly.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 437, level: 3, correct: "He found a rare old coin.", hint: "Two adjectives.", feedback: "Correct!" },
    { id: 438, level: 3, correct: "The noisy crowd cheered loudly.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 439, level: 3, correct: "She baked a sweet chocolate cake.", hint: "Two adjectives.", feedback: "Correct!" },
    { id: 440, level: 3, correct: "The wild horse ran away.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" },
    { id: 441, level: 3, correct: "I saw a tiny green frog.", hint: "Two adjectives.", feedback: "Correct!" },
    { id: 442, level: 3, correct: "The heavy rain caused a flood.", hint: "Adjective + Subject + Verb + Object", feedback: "Correct!" },
    { id: 443, level: 3, correct: "He spoke to the old man.", hint: "Adjective before object.", feedback: "Correct!" },
    { id: 444, level: 3, correct: "The bright sun hurt my eyes.", hint: "Adjective + Subject + Verb + Object", feedback: "Correct!" },
    { id: 445, level: 3, correct: "She cleaned the dirty floor.", hint: "Adjective before object.", feedback: "Correct!" },
    { id: 446, level: 3, correct: "He fixed the broken chair.", hint: "Adjective before object.", feedback: "Correct!" },
    { id: 447, level: 3, correct: "The lazy cat slept all day.", hint: "Adjective + Subject + Verb + Time", feedback: "Correct!" },
    { id: 448, level: 3, correct: "We ate fresh hot bread.", hint: "Two adjectives.", feedback: "Correct!" },
    { id: 449, level: 3, correct: "The strong wind blew hard.", hint: "Adjective + Subject + Verb + Adverb", feedback: "Correct!" }
    //add custom sentences from here


];